


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/BookVault
spring.datasource.username=weeb_coder
spring.datasource.password=Code4life
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Docker
spring.docker.compose.enabled=false
