spring.application.name=ReadingVaultBackEnd

#Server port 
server.port=8080

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/BookVault
spring.datasource.username=weeb_coder
spring.datasource.password=Code4life
spring.datasource.driver-class-name=com.postgresql.Driver

#JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Configuration